/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AidCenterAssetsRequested } from './aidCenterAssetsRequested';
import { AidCenterOrganizationContact } from './aidCenterOrganizationContact';
import { AidCenterOrganization } from './aidCenterOrganization';


export interface AidCenter { 
    readonly id?: string;
    organization: AidCenterOrganization;
    contact: AidCenterOrganizationContact;
    geo_location: object;
    readonly assets_requested?: Array<AidCenterAssetsRequested>;
    readonly assets_fulfilled?: Array<AidCenterAssetsRequested>;
    readonly assets_overloaded?: Array<AidCenterAssetsRequested>;
    readonly feed?: object;
    note?: string;
    name: string;
    slug: string;
    photo?: Blob;
    country_code: string;
    postal_code: string;
    city: string;
    address: string;
    call_required?: AidCenter.CallRequiredEnum | null;
    money_accepted?: boolean | null;
    money_description?: string;
    campaign_ending_on?: string | null;
}
export namespace AidCenter {
    export type CallRequiredEnum = 'required' | 'suggested' | 'denied';
    export const CallRequiredEnum = {
        Required: 'required' as CallRequiredEnum,
        Suggested: 'suggested' as CallRequiredEnum,
        Denied: 'denied' as CallRequiredEnum
    };
}


